### PR TITLE
Fix getting Stages with JavaFX11 / Editing files with Windows+IntelliJ

### PR DESCRIPTION
**Pull request by FlorianKirmaier**
Fix getting Stages with JavaFX11.
CSSFX now also works with Windows which are no Stages.

I would appreciate a new stable version with this fix.

### CODE REVIEW

**Comment by FlorianKirmaier** [comment]
@McFoggy 
I would appreciate it if you can find some time to make a new release with the fix!

**Comment by McFoggy** [comment]
I want to be sure the code changes are fully backward compatible, and to keep the namings of variables in a good shape. Let me few days please.

**Comment by FlorianKirmaier** [comment]
Okay, Great!

Should I change all variable names from stage to window, according to the type? 
This would change quite a lot.

The method onlyFor also should take Window instead of Stage, but it would be a minor API change.
What do you think?

**Comment by FlorianKirmaier** [comment]
I've also added a fix for #19

**Comment by McFoggy** [comment]
Hi Florian, sorry for the delay. I took over your changes and pushed enhancements for renaming a bit the things. 

Can you have a quick look at [PR18](https://github.com/McFoggy/cssfx/tree/PR18) branch if it suits your needs?

**Comment by FlorianKirmaier** [comment]
@McFoggy 
Your changes to your branch are looking good.
Florian

**Comment by McFoggy** [comment]
closed with 9de3bc996b32b05f816950c17027fb70e11f7198

version `11.1.0` has just been released. Wait for central sync (or use sonatype repo).

Thanks again for your contribution.

**Pull request closed without merging**
