### PR TITLE
relocate & refactor project

### LINKED ISSUE #31: provide module info
as stated in #30 cssfx is not modular.

we should remedy to that by:

- either fixing the automatic module name
- provide real module-info

Also the module name to expose must be defined:
1. `cssfx` it is the current automatic module name:
    * good for compatibility reasons
    * bad for potential collisions in global namespace
1. `org.fxmisc.cssfx`
    * avoid collisions by using the current groupId namespace
    * bad because out control, domain is owned by [Thomas Mikula](https://github.com/TomasMikula)
1. `fr.brouillard.cssfx`
    * avoid collisions by using an owned groupId namespace
    * its a controlled namespace (including for deployment in central)

### PR DESCRIPTION
**Pull request by McFoggy**
move java package to fr.brouillard.oss.cssfx
change maven GroupId to fr.brouillard.oss
change module name to fr.brouillard.oss.cssfx

fixes #31

### CODE REVIEW

**Comment by McFoggy** [comment]
@FlorianKirmaier @rustybox can you have a look please ?

**Comment by rustybox** [comment]
LGTM - but I don't think my opinions should hold much weight here :)

**Comment by McFoggy** [comment]
@rustybox all opinions are good to hear. As you were interested in using the library in a modular environment your voice count for me.

**Comment by FlorianKirmaier** [comment]
LGTM
But I haven't tested it with the module-system because I usually avoid it in my projects.

**Comment by rustybox** [comment]
I gave it a go locally

steps

cloned repo, check out refactor branch

```bash
$ mvn install
$ cd ~/.m2/repository/fr/brouillard/oss/cssfx/11.2.3-SNAPSHOT
$ jar --file=cssfx-11.2.3-SNAPSHOT.jar --describe-module

# fr.brouillard.oss.cssfx@11.2.3-SNAPSHOT automatic
```
Added to my app pom.xml
```xml
<dependency>
    <groupId>fr.brouillard.oss</groupId>
    <artifactId>cssfx</artifactId>
    <version>11.2.3-SNAPSHOT</version>
</dependency>
```

Added to my app module-info.java

```java
  requires fr.brouillard.oss.cssfx;
```

And to my Application 
```java
import fr.brouillard.oss.cssfx.CSSFX;
...
CSSFX.start();
```

this works for me.

**Comment by McFoggy** [comment]
I'll merge and deploy `11.3` later today, thanks for the feedback.

**Pull request merged**
