### PR TITLE
Many important improvements

### PR DESCRIPTION
**Pull request by FlorianKirmaier**
Guess it's time for some improvements for CSSFX.

The improvements are:
 - CleanupDetector uses now WeakReferences instead of PhantomReferences - which helps analyze heap dumps, and also should improve the performance.
 - Updated JMemoryBuddy
 - Started CSSFX multiple times is now prevented. This actually caused problems in production.
 - It's now possible to globally disable CSSFX with the system property `-Dcssfx.disable=true`

### CODE REVIEW

**Comment by McFoggy** [comment]
@FlorianKirmaier I have updated a little bit your branch, if you agree with the changes then we can integrate the branch. Let me know.

**Comment by FlorianKirmaier** [comment]
@McFoggy Thank you for the quick response!

**CleanupListener**
The changes to the CleanupListener are ok - but not necessary.
I've copied the class from here: https://github.com/Sandec/JMemoryBuddy/blob/master/src/main/java/de/sandec/jmemorybuddy/CleanupDetector.java .

**CSSFX**
There is currently the global start method, and versions for Scene and Window, which only start CSSFX for a specific scene/window.
I only prevented multiple calls to the global start method - because calling it multiple times doesn't have any effect.
But calling the other start-methods multiple times is reasonable.
So either, the check should be moved ab to the global start method, or the start method with scene/window should be removed. Personally, I would prefer removing them. I've never used it, and when I'm using CSSFX, I always start it globally.

**Comment by McFoggy** [comment]
merged via 73c84ffe1ead1a8b4db5ec4bc809ed6dd01ef3fa

**Comment by McFoggy** [comment]
released inside `11.5.0`, published to sonatype waiting sync with central maven repo.

**Comment by FlorianKirmaier** [comment]
@McFoggy 
Thank you for the new release!

**Pull request closed without merging**
